server:
  port: 8888

spring:
  profiles:
    active: dev

# SQL日志
logging:
  level:
    com.space.logindemo.logindemo.mapper: debug

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**.xml

# token配置
token:
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30
  header: Authorization

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.space.logindemo.logindemo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
